function trialdetails = importTrialDetails(filename)
%IMPORTFILE Import data from a text file
%  TRIALDETAILSPCATRUE20240625024108 = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  TRIALDETAILSPCATRUE20240625024108 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  trialdetailsPCATrue20240625024108 = importfile("C:\Users\jjm53\OneDrive - University of Bath\robotic_finger\trial_details_PCATrue_20240625-024108.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Jun-2024 10:16:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
%opts = delimitedTextImportOptions();%"NumVariables", 7);
opts = detectImportOptions(filename);
% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
%opts.VariableNames = ["trial", "HP_H_UNITS", "HP_LSTM_UNITS", "HP_EPOCHS", "HP_BATCH", "HP_LR", "HP_L2_LAMBDA"];
%opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
trialdetails = readtable(filename, opts);

trialdetails = rmmissing(trialdetails);

if contains(filename, "PCATrue")
    trialdetails(:,"PCA") = repmat({true}, height(trialdetails), 1) ;
else
    trialdetails(:,"PCA") = repmat({false}, height(trialdetails), 1);


end