function EXP0r20s90dist5delay100 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EXP0R20S90DIST5DELAY100 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  EXP0R20S90DIST5DELAY100 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  EXP0r20s90dist5delay100 = importfile("C:\Users\jjm53\OneDrive - University of Bath\robotic_finger\collected_data_previous\EXP0_r20_s90_dist5_delay100.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Jun-2024 15:21:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "time", "accx", "accy", "accz", "gx", "gy", "gz", "tetax", "tetay", "pressure"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
EXP0r20s90dist5delay100 = readtable(filename, opts);

end